export const mySubsArray = [
  {
    id: '1',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '2',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '3',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '4',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '5',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '6',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '7',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '8',
    is_active: true,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '9',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '10',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '11',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '12',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '13',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '14',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '15',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
  {
    id: '16',
    is_active: false,
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
    promo: 'rufnfi8vj',
    service_link: 'https://www.ivi.ru/',
  },
];

export const availableSubsArray = [
  {
    id: '17',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
  {
    id: '18',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
  {
    id: '19',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
  {
    id: '20',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
  {
    id: '21',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
  {
    id: '22',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
  {
    id: '23',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
  {
    id: '24',
    name: 'Изи Иви',
    description: 'Подписка на фильмы',
    date: '15.04.2024',
    cost: '200',
    logo: 'https://propostuplenie.ru/images/navigator-data-800x800_8/article/ivi_1000x523-jpg',
    duration: 'мес',
    cashBack: '10',
  },
];

export const user = {
  phone_number: '9211231212',
  first_name: 'string',
  middle_name: 'string ',
  last_name: 'string',
  account_balance: '15000.00',
  cashback: '151.00',
};
